### ISSUE TITLE
How can I process Non English language Training Data

### ISSUE THREAD

**Issue by sarvdanandarya** [Nirespire/FAQBot#1]
I am Creating a Bot which includes the Question and answers in Hindi language, but the Character are non readable.
how should I make the bot learn Hindi characters ?
![Capture](https://user-images.githubusercontent.com/20046063/57934358-32638800-78dd-11e9-915c-f26540098139.PNG)

**Comment by Nirespire** [comment]
@sarvdanandarya That's really interesting. Just curious, what terminal are you using in that screenshot? I'm wondering if it's an issue with the terminal displaying Hindi characters or something with the application not displaying the characters properly.

**Comment by sarvdanandarya** [comment]
Hi @Nirespire , I am using windows command line tool.
the queries are not readable so not getting answers for them.

**Comment by Nirespire** [comment]
@sarvdanandarya so after some digging, it looks like this is probably due to a limitation in the `natural` node module used for creating the classifier from the inputted test. `natural` doesn't have a tokenizer for Hindi, but it sounds like these opportunity to add that tokenizer to the library and use that updated version in this project to enable support for Hindi characters.

Related Issue from `natural` I found:  https://github.com/NaturalNode/natural/issues/314
Current tokenizers supported by `natural`: https://github.com/NaturalNode/natural#tokenizers
Example PR to that repo for adding a language tokenizer, Dutch in this example: https://github.com/NaturalNode/natural/pull/135/files
